
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Entry tCambio;
	private global::Gtk.Button btnCambio;
	private global::Gtk.Label label2;
	private global::Gtk.Entry txtPesos;
	private global::Gtk.Entry txtDolares;
	private global::Gtk.Label label3;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Cambio de Divisas");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tCambio = new global::Gtk.Entry ();
		this.tCambio.CanFocus = true;
		this.tCambio.Name = "tCambio";
		this.tCambio.Text = global::Mono.Unix.Catalog.GetString ("13.10");
		this.tCambio.IsEditable = false;
		this.tCambio.HasFrame = false;
		this.tCambio.InvisibleChar = '●';
		this.fixed1.Add (this.tCambio);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.tCambio]));
		w1.X = 61;
		w1.Y = 235;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnCambio = new global::Gtk.Button ();
		this.btnCambio.CanFocus = true;
		this.btnCambio.Name = "btnCambio";
		this.btnCambio.UseUnderline = true;
		this.btnCambio.Label = global::Mono.Unix.Catalog.GetString ("Cambiar");
		this.fixed1.Add (this.btnCambio);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnCambio]));
		w2.X = 106;
		w2.Y = 157;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Dolares");
		this.fixed1.Add (this.label2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
		w3.X = 109;
		w3.Y = 19;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtPesos = new global::Gtk.Entry ();
		this.txtPesos.CanFocus = true;
		this.txtPesos.Name = "txtPesos";
		this.txtPesos.IsEditable = true;
		this.txtPesos.MaxLength = 5;
		this.txtPesos.InvisibleChar = '●';
		this.txtPesos.Xalign = 0.5F;
		this.fixed1.Add (this.txtPesos);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtPesos]));
		w4.X = 56;
		w4.Y = 124;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtDolares = new global::Gtk.Entry ();
		this.txtDolares.TooltipMarkup = "Ingrese cantidad en dolares";
		this.txtDolares.CanFocus = true;
		this.txtDolares.Name = "txtDolares";
		this.txtDolares.IsEditable = true;
		this.txtDolares.MaxLength = 5;
		this.txtDolares.InvisibleChar = '●';
		this.txtDolares.Xalign = 0.5F;
		this.fixed1.Add (this.txtDolares);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.txtDolares]));
		w5.X = 50;
		w5.Y = 43;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Pesos");
		this.fixed1.Add (this.label3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
		w6.X = 115;
		w6.Y = 92;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 278;
		this.DefaultHeight = 314;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnCambio.Clicked += new global::System.EventHandler (this.cambioClick);
	}
}
